/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bitcamp.myapp;

import com.bitcamp.myapp.handler.BoardHandler;
import com.bitcamp.myapp.handler.ScheduleHandler;
import com.bitcamp.util.ArrayList;
import com.bitcamp.util.LinkedList;
import com.bitcamp.util.MenuPrompt;

public class App {

  public static void main(String[] args) {

    MenuPrompt prompt = new MenuPrompt();
    prompt.appendBreadcrumb("메인", getMenu());

    ScheduleHandler schduleHandler = new ScheduleHandler(prompt, "스케줄", new LinkedList());
    BoardHandler boardHandler = new BoardHandler(prompt, "게시글", new ArrayList());

    printTitle();
    prompt.printMenu();

    String menuNo;

    while (true) {
      menuNo = prompt.inputMenu();
      if (menuNo.equals("0")) {
        break;
      } else if (menuNo.equals("menu")) {
        prompt.printMenu();
      } else if (menuNo.equals("1")) {
        schduleHandler.execute();
      } else if (menuNo.equals("2")) {
        boardHandler.execute();
      } else {
        System.out.println("올바르지 않은 메뉴 번호입니다.");
      }
    }
    prompt.close();
  }

  static String getMenu() {
    StringBuilder menu = new StringBuilder();
    menu.append("1. 스케줄\n");
    menu.append("2. 게시글\n");
    menu.append("0. 종료\n");

    return menu.toString();
  }

  static void printTitle() {
    System.out.println("스케줄 관리 애플리케이션");
    System.out.println("----------------------------------");
  }

}
