/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bitcamp;

public class App {
  public static void main(String[] args) {
    System.out.println("스캐줄 관리 애플리케이션");
    int intVal = Integer.MAX_VALUE;
    long longVal = Long.MAX_VALUE;
    float floatVal = Float.MAX_VALUE;
    double doubleVal = Double.MAX_VALUE;
    char ch = 'c';
    String str = "string";
    boolean bool = true;
    System.out.printf("%d \n%d \n%f \n%f \n%c \n%s \n%b \n",
        intVal, longVal, floatVal, doubleVal, ch, str, bool);
  }
}
