/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bitcamp.myapp;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.net.ServerSocket;
import java.net.Socket;
import com.bitcamp.myapp.dao.BoardDao;
import com.bitcamp.myapp.dao.BoardListDao;
import com.bitcamp.myapp.dao.ScheduleDao;
import com.bitcamp.myapp.dao.ScheduleListDao;
import com.bitcamp.myapp.vo.Board;
import com.bitcamp.myapp.vo.Schedule;
import com.bitcamp.net.RequestEntity;
import com.bitcamp.net.ResponseEntity;

public class ServerApp {

  int port;
  ServerSocket serverSocket;

  ScheduleDao scheduleDao = new ScheduleListDao("schedule.json");
  BoardDao boardDao = new BoardListDao("board.json");
  BoardDao readingDao = new BoardListDao("reading.json");

  public ServerApp(int port) throws Exception {
    this.port = port;
  }

  public void close() throws Exception {
    serverSocket.close();
  }

  public static void main(String[] args) throws Exception {
    if (args.length < 1) {
      System.out.println("실행 예) java ...  bitcamp.myapp.ServerApp 포트번호");
      return;
    }

    ServerApp app = new ServerApp(Integer.parseInt(args[0]));
    app.execute();
    app.close();
  }

  public void execute() throws Exception {
    System.out.println("[Schedule management 서버 애플리케이션]");

    this.serverSocket = new ServerSocket(port);
    System.out.println("서버 실행 중...");

    Socket socket = serverSocket.accept();
    DataInputStream in = new DataInputStream(socket.getInputStream());
    DataOutputStream out = new DataOutputStream(socket.getOutputStream());

    while (true) {

      RequestEntity request = RequestEntity.fromJson(in.readUTF());

      String command = request.getCommand();
      System.out.println(command);

      ResponseEntity response = new ResponseEntity();

      if (command.equals("quit")) {
        break;

      }
      switch (command) {
        case "board/list":
          response.status(ResponseEntity.SUCCESS).result(boardDao.list());
          break;

        case "board/insert":
          boardDao.insert(request.getObject(Board.class));
          response.status(ResponseEntity.SUCCESS);
          break;

        case "board/findBy":
          Board board = boardDao.findBy(request.getObject(Integer.class));
          if (board != null) {
            response.status(ResponseEntity.SUCCESS).result(board);
          } else {
            response.status(ResponseEntity.FAILURE).result("해당 번호의 게시글이 없습니다");
          }
          break;

        case "board/update":
          response.status(ResponseEntity.SUCCESS)
              .result(boardDao.update(request.getObject(Board.class)));
          break;

        case "board/remove":
          response.status(ResponseEntity.SUCCESS)
              .result(boardDao.remove(request.getObject(Integer.class)));
          break;


        case "schedule/list":
          response.status(ResponseEntity.SUCCESS).result(scheduleDao.list());
          break;

        case "schedule/insert":
          scheduleDao.insert(request.getObject(Schedule.class));
          response.status(ResponseEntity.SUCCESS);
          break;

        case "schedule/findBy":
          Schedule schedule = scheduleDao.findBy(request.getObject(Integer.class));
          if (schedule != null) {
            response.status(ResponseEntity.SUCCESS).result(schedule);
          } else {
            response.status(ResponseEntity.FAILURE).result("해당 번호의 게시글이 없습니다");
          }
          break;

        case "schedule/update":
          response.status(ResponseEntity.SUCCESS)
              .result(scheduleDao.update(request.getObject(Schedule.class)));
          break;

        case "schedule/remove":
          response.status(ResponseEntity.SUCCESS)
              .result(scheduleDao.remove(request.getObject(Integer.class)));
          break;
        default:
          response.status(ResponseEntity.ERROR).result("해당 명령을 지원하지 않습니다.");
      }

      out.writeUTF(response.toJson());
    }

  }


}
