/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bitcamp.myapp;


import java.util.Scanner;

public class App {
  public static void main(String[] args) {
    System.out.println("스캐줄 관리 애플리케이션");

    Scanner scanner = new Scanner(System.in);

    final int MAX_SIZE = 100;

    String[] scheduleTitle = new String[MAX_SIZE];
    String[] startTime = new String[MAX_SIZE];
    String[] endTime = new String[MAX_SIZE];

    int count = 3;

    for (int i = 0; i < count; i++) {
      System.out.println("일정 제목을 입력하세요");
      scheduleTitle[i] = scanner.nextLine();

      System.out.println("일정 시작 날짜와 시간을 입력하세요");
      System.out.println("ex)2023-06-05 16:30");
      startTime[i] = scanner.nextLine();
      // String str = scanner.nextLine();
      // double startTimeInt = Double.parseDouble(str.replaceAll("-", "").replaceAll("
      // ", "").replaceAll(":", ""));

      System.out.println("일정 종료 날짜와 시간을 입력하세요");
      System.out.println("ex)2023-06-06 20:00");
      endTime[i] = scanner.nextLine();
      // str = scanner.nextLine();
      // double endTimeInt = Double.parseDouble(str.replaceAll("-", "").replaceAll("
      // ", "").replaceAll(":", ""));}
    }

    for (int i = 0; i < count; i++) {
      System.out.println(scheduleTitle[i]);
      System.out.println(startTime[i]);
      System.out.println(endTime[i]);
    }

    scanner.close();
  }
}
